### ISSUE TITLE
Provide hash function by approval/clear program pages

### ISSUE THREAD

**Issue by barnjamin** [algorand-devrel/beaker#123]
If a precompiled approval or clear program is >4k the hash function will break.

Allow specification of hash page during a call to `hash`  to allow the page to be loaded to the stack

**Comment by JuWeber99** [comment]
Hi @barnjamin ! Can you assign me? Thanks!

**Comment by JuWeber99** [comment]
Use Parent and child app. The child app is included as precompile in the Parent. The Parent has 1 specific function for the test. 

This ABI Function will receive an application call txn as argument which will be an app creation txn for the child app. The approval_program_pages - TxnArray can then be used to compare the defacto approval pages from the call hashed with sha256 to the values generated by the .hash() function for the respective index of the program page idx which shall be passed as optional param to the .hash() function
