### ISSUE TITLE
Remove examples directory from install 

### ISSUE THREAD

**Issue by barnjamin** [algorand-devrel/beaker#132]
The beaker-pyteal package ships with the examples folder which gets installed to `site-packages`, it should not.

**Comment by CiottiGiorgio** [comment]
#135 fixes this but it's worth noting that `pyteal` package has the same issue so it's even difficult to reproduce this behavior because often times the `example` folder in `pyteal` package will overwrite the `example` folder in `beaker-pyteal` package.
