### ISSUE TITLE
"invalid box reference" when using uint64 bytes in box names

### ISSUE THREAD

**Issue by giraffekey** [algorand-devrel/beaker#180]
There are some use cases for using uint64 values in box names such as a 2D coordinate system:

```python
from pyteal import *
from beaker import *
from beaker.lib.storage import Mapping

Position = abi.Tuple2[abi.Uint64, abi.Uint64]

class Grid(Application):
	values = Mapping(Position, abi.Uint64, Bytes("v"))

	@external
	def get_value(self, pos: Position, *, output: abi.Uint64):
		return self.values[pos].store_into(output)

	@external
	def set_value(self, pos: Position, value: abi.Uint64):
		return self.values[pos].set(value)
```

However, when deploying to testnet and attempting to call either of these methods with the JS SDK, the transaction fails and returns the error "logic eval error: invalid Box reference v����������������.".

I figure the box names are being set to something like the following:

```python
Concat(Bytes("v"), Itob(pos[0].get()), Itob(pos[1].get()))
```

This should be a 17-byte name and the max name size is 64 bytes, so I don't believe that is the issue.

Is there a problem with using uint64 bytes in box names? Are there byte values that cannot be used in box names (something to do with UTF-8 maybe)? Is this a problem with the JS SDK or the smart contract?

What are some potential workarounds?

**Comment by barnjamin** [comment]
This is likely an issue with the transaction calling the app not passing the appropriate box references. 

Can you post what the box refs you're passing look like?

**Comment by barnjamin** [comment]
for reference, heres what a box ref in an app call using the js-sdk might look like https://github.com/algorand-devrel/demo-abi/blob/master/js/abi.ts#L53-L71

**Comment by giraffekey** [comment]
I must have misunderstood how to use AtomicTransactionComposer correctly because I was not passing a "boxes" field at all. I added some code to my front-end that converts integers to arrays and now everything is working.
