### ISSUE TITLE
Provide functions to get a sandbox KMD client and the default wallet

### ISSUE THREAD

**Issue by oysterpack** [algorand-devrel/beaker#182]
The `beaker.sandbox.clients` provides functions to get node and indexer clients. For completeness, provide functions to get a KMD client and the default wallet.

The functions should be added to the `beaker.sandbox.kmd` module:
```python

from algosdk import kmd

def get_client() -> kmd.KMDClient:
    return kmd.KMDClient(
        kmd_token=DEFAULT_KMD_TOKEN,
        kmd_address=DEFAULT_KMD_ADDRESS
    )

def get_sandbox_default_wallet() -> wallet.Wallet:
    return wallet.Wallet(
        wallet_name=DEFAULT_KMD_WALLET_NAME,
        wallet_pswd=DEFAULT_KMD_WALLET_PASSWORD,
        kmd_client=get_client()
    )

```

**Comment by barnjamin** [comment]
seems reasonable, it looks close, you want to pr it?

**Comment by oysterpack** [comment]
submitted PR https://github.com/algorand-devrel/beaker/pull/183

**Comment by oysterpack** [comment]
DONE - PR was merged

https://github.com/algorand-devrel/beaker/commit/87e7310426e2b5d3fd05c41a03ccd7972be53b3d
