### ISSUE TITLE
Beaker added on awesomealgo under python dev section

### ISSUE THREAD

**Issue by aorumbayev** [algorand-devrel/beaker#2]
Hey guys, this isn't an issue - just wanted to say awesome stuff with this project. 

Just listed it on awesome algo -> https://github.com/aorumbayev/awesome-algorand/pull/75. 

If you are interested to come and talk about it on the podcast just fill the signup form https://2c5n1ed3kz6.typeform.com/to/pAP5oPFx :-) 

Regards,
Al

**Comment by barnjamin** [comment]
nice! thank you!
