### ISSUE TITLE
ApplicationClient.get_sender() does not handle custom TransactionSigner implementations properly

### ISSUE THREAD

**Issue by oysterpack** [algorand-devrel/beaker#213]
Below is the ApplicationClient.get_sender() code. I have a custom TransactionSigner implementation that I want to use. Even though, I specify a sender and signer when I create an ApplicationClient instance. I expect the sender that is explicitly specified to be used as the default sender. However, the current logic ignores the sender if the signer is set.

Even though I have specified a sender (and signer), I have to specify the sender for each ApplicationClient call, e.g.

If I try to create the contract with the following line of code:
`app_client.create()`
it fails with the error msg : "No sender provided"

To make it work, I have to specify the sender again, even though I specified it at construction time as the default sender:
`app_client.create(sender=sender)`

**Comment by oysterpack** [comment]
After updating my dependencies the situation went from bad to worse ... caused by an update in the beaker dependency: algokit-utils v1.0.1. My work around no longer works around the issue.

**beaker-pyteal**
```python
class ApplicationClient:
    
    def get_signer(self, signer: TransactionSigner | None = None) -> TransactionSigner:
        signer, sender = self._app_client._resolve_signer_sender(signer, None) # NONE IS PASSED IN WHICH BREAKS DOWN FOR CUSTOM IMPLEMENTATIONS OF TransactionSigner
        return signer
```

**algokit-utils**
```python
class ApplicationClient:

    def _resolve_signer_sender(
        self, signer: TransactionSigner | None, sender: str | None
    ) -> tuple[TransactionSigner, str]:
        resolved_signer = signer or self.signer
        if not resolved_signer:
            raise Exception("No signer specified")
        if sender is not None:
            resolved_sender = sender
        elif signer is None and self.sender is not None:
            resolved_sender = self.sender
        else:
            resolved_sender = _get_sender_from_signer(resolved_signer) # THIS BRANCH IS INVOKED WHEN SENDER IS NONE
        return resolved_signer, resolved_sender     
```

**Comment by barnjamin** [comment]
cc @robdmoore @daniel-makerx

**Comment by oysterpack** [comment]
To fix the core issue, I would recommend the following: add a get_sender() abstract method to TransactionSigner

```python
class TransactionSigner(ABC):
    """
    Represents an object which can sign transactions from an atomic transaction group.
    """
    @abstractmethod
    def sign_transactions(
        self, txn_group: List[transaction.Transaction], indexes: List[int]
    ) -> List[GenericSignedTransaction]:
        ...

    @abstractmethod
    def get_sender(self) -> str:
        ...    
```

**Comment by daniel-makerx** [comment]
Hi @oysterpack, thanks for the report. I am preparing a fix for this issue, such that if a sender is provided (either via the ApplicationClient constructor or when calling the app) then it will be used. This should solve your particular issue.

I agree that the `isinstance` checks are not ideal, however in this instance we couldn't just add an abstract method as TransactionSigner is not part of the beaker library (it is defined in algosdk).
