### ISSUE TITLE
Getting error for a nested app call with txn parameter

### ISSUE THREAD

**Issue by smonn** [algorand-devrel/beaker#231]
I'm not sure this is an issue with a) my calling code, b) my smart contracts, c) beaker, d) pyteal, or c) algosdk. But in case it's one of the latter three I wanted to share this error.

For context, I have two smart contracts, let's call them `app_a` and `app_b`. `app_a.method_1` requires that you include a payment transaction when calling it. When using Beaker's `ApplicationClient` for `app_a`, that is trivial and would look something like this:

```python
app_a_client.call(
    app_a.method_1,
    payment=TransactionWithSigner(
        txn=PaymentTxn(
            amt=1000000,
            receiver=app_a_client.app_addr,
            sender=sender_addr,
            sp=algod_client.suggested_params(),
        ),
        signer=sender_signer,
    ),
)
```

`app_b` in turn has `method_2` which requires you to embed a call to `app_a.method_1`. I'm not entirely sure how to do this, but this is what I came up with, which is currently failing:

```python
atc = AtomicTransactionComposer()
atc.add_method_call(
    app_id=app_a_client.app_id,
    sender=sender_addr,
    sp=algod_client.suggested_params(),
    method=app_a_contract.get_method_by_name("method_1"),
    method_args=[
        TransactionWithSigner(
            txn=PaymentTxn(
                sender=sender_addr,
                amt=1000000,
                receiver=app_a_client.app_addr,
                sp=algod_client.suggested_params(),
            ),
            signer=sender_signer,
        ),
    ],
    signer=sender_signer,
)

app_b_client.call(
    app_b.method_2,
    app_a_id=app_a_client.app_id,
    method_1_txn=atc.build_group()[0],
)
```

Is this possible to do a different way? Or is it not possible at all due to some technical limitation?

The error:

```
Failed: [undefined]algosdk.error.AtomicTransactionComposerError: expected TransactionWithSigner as method argument, but received: <algosdk.atomic_transaction_composer.TransactionWithSigner object at 0xffff9db33bd0>
algod_client = <algosdk.v2client.algod.AlgodClient object at 0xffff9def9590>
app_client = <beaker.client.application_client.ApplicationClient object at 0xffff9e0f7450>
```

**Comment by smonn** [comment]
Using a plain `ApplicationCallTxn` seems to work, just need to specify `0` as the txn group index for the parameter:

```python
atc = AtomicTransactionComposer()
atc.add_transaction(
    TransactionWithSigner(
        PaymentTxn(
            sender_addr,
            algod_client.suggested_params(),
            app_a_client.app_addr,
            1000000,
        ),
        sender_signer,
    )
)

app_b_client.call(
    app_b.method_2,
    app=app_a_client.app_id,
    method_1_txn=TransactionWithSigner(
        ApplicationCallTxn(
            sender_addr,
            algod_client.suggested_params(),
            app_a_client.app_id,
            on_complete=OnComplete.NoOpOC,
            app_args=[app_a_contract.get_method_by_name("method_1").get_selector(), 0],
        ),
        sender_signer,
    ),
    atc=atc,
)
```

**Comment by barnjamin** [comment]
Interesting, can you please post the versions of everything? I'd like to replicate to find the issue.

With js, we get a similar type of error when multiple versions of the sdk are included because of an instanceof check on Transaction type so wondering if python has a similar issue

**Comment by barnjamin** [comment]
I see now, the Error message is not great.


Adding prints before the error is raised: 
```py    
print(isinstance(method_args[i], TransactionWithSigner))
print(arg.type)
print(method_args[i].txn)
print(abi.check_abi_transaction_type(arg.type, method_args[i].txn))
```
https://github.com/algorand/py-algorand-sdk/blob/develop/algosdk/atomic_transaction_composer.py#L498-L507

results in 
```
True
appl
{'sender': '4HB5CWU5UMSIGTT4A64Z3P5WM3Z7ASKYAPA5DB6BOGJOFXROJICJNIJFSE', 'fee': 1000, 'first_valid_round': 144, 'last_valid_round': 1144, 'note': None, 'genesis_id': 'sandnet-v1', 'genesis_hash': 'K5Zkh41eX6WkakcHpgMoVt2KeNVSHJXLGVL84QYcE0A=', 'group': b'+\xb0\xc1\xf8\xd7v\xd5~g\xee\t7q\xb7\xf6\xfc\xc9J\xcc\xdc\xfa\x84fq\x83\xbfv\xcbBZ\x1a\xd3', 'lease': None, 'type': 'pay', 'rekey_to': None, 'receiver': 'LNFBHX2HDFVPJKPCK3RTSSA3KBJXAVEGG54P4AN3TQUWRHSZJHQLOAELB4', 'amt': 1000000, 'close_remainder_to': None}
False
```

Because meth2 is expecting an `appl` but the 0th transaction is the `pay` since the abi requires transactions in a method signature to come _before_ the app call.

Changing the `0` to a `1` for the first one like `build_group()[1]` gets it to successfully execute but fails at runtime with group index issues.

**Comment by barnjamin** [comment]
https://github.com/algorand-devrel/beaker/blob/atc-weird-demo/examples/simple/atc_wat.py#L37-L58 heres a way to do this without populating the method selector/ptxn group index manually
