### ISSUE TITLE
Value `.set()` type check

### ISSUE THREAD

**Issue by cusma** [algorand-devrel/beaker#26]
Upon `.set()` value of an Application or Account state variable Beaker's type checker verifies the consistency of the assignment with respect to variable's `stack_type`, which is definitely good to ensure robust typing abstraction but fails on the assignation of unknown `MaybeValue` that can potentially result in a `TealType.anyType` (e.g. in case of `ScratchLoad` or `GetEx`).

Beaker type checker should handle these cases properly.

**Comment by barnjamin** [comment]
Do you have an example handy?

**Comment by cusma** [comment]
This could be potentially one:

```python
class MyApp(Application):
    my_var: Final[ApplicationStateValue] = ApplicationStateValue(
        stack_type=TealType.uint64,
    )

    @create
    def create(self) -> Expr:
        ex_var = App.globalGetEx(Int(42), Bytes("foo"))
        return Seq(
            ex_var,
            self.my_var.set(ex_var.value()),
            Approve(),
        )
```

**Comment by barnjamin** [comment]
I guess the only way to handle this is if it is a matching type exactly or `anytype`. 

I could also not do any type checking and let it fail at runtime if its invalid 🤔

**Comment by cusma** [comment]
> I could also not do any type checking and let it fail at runtime if its invalid 🤔 

I would definitely keep the type checking on compiling.

I'm more inclined to have another `.set_maybe()` method or a default `maybe=False` parameter in `.set()` to consciously disabled the type checking when needed.

**Comment by barnjamin** [comment]
added a check for any, closing this
