### ISSUE TITLE
Align ARC-20 beakerized contract to Smart ASA reference implementation

### ISSUE THREAD

**Issue by cusma** [algorand-devrel/beaker#50]
Just here as reminder for future: [arc20](https://github.com/algorand-devrel/beaker/blob/master/beaker/contracts/arcs/arc20.py) "beakerized" implementation should be aligned with the [Smart ASA reference implementation](https://github.com/algorandlabs/smart-asa) to avoid spreading of multiple versions around.

1. [Update of ARC-20 getters](https://github.com/algorandfoundation/ARCs/pull/91/commits/7ed37aadf6247084da4144720f511ccc4e2f17e8);
2. [Relative reference of transaction indexes](https://github.com/algorandlabs/smart-asa/blob/main/smart_asa_asc.py#L652) in `CloseOut`;

**Comment by barnjamin** [comment]
Removed contracts from this repo, closing this issue
