### ISSUE TITLE
Methods ordering is not deterministic

### ISSUE THREAD

**Issue by cusma** [algorand-devrel/beaker#71]
### Current behaviours
Executing multiple times something like:

```python
def my_app_compile() -> None:

    my_app = MyApp()

    with open("my_app_abi.json", "w") as f:
        f.write(json.dumps(my_app.contract.dictify(), indent=4))

    with open("my_app_approval.teal", "w") as f:
        f.write(my_app.approval_program)

    with open("my_app_clear.teal", "w") as f:
        f.write(my_app.clear_program)
```

Results in TEAL files an in a JSON file with methods ordered in different ways.

### Expected behaviours
No `diff` between multiple executions.

**Comment by cusma** [comment]
It could be related to: https://github.com/algorand/pyteal/issues/517

**Comment by barnjamin** [comment]
Weird, I'm not sure why it was happening exactly but I added a `sorted` line to make sure we're processing them in order https://github.com/algorand-devrel/beaker/blob/master/beaker/application.py#L75
