### ISSUE TITLE
Support for method overriding

### ISSUE THREAD

**Issue by CiottiGiorgio** [algorand-devrel/beaker#78]
As per ARC4, more than one method can have the same name so long as it has different signature.

PyTeal router provides this feature but it's not easy to implement in Beaker because Python will elide methods with the same name. This can be circumvented by adding a keyword-only arg `name` to `external` decorator.

**Comment by CiottiGiorgio** [comment]
Currently building [here](https://github.com/CiottiGiorgio/beaker/tree/feature/method-overriding).

**Comment by barnjamin** [comment]
pr'd in #84

**Comment by CiottiGiorgio** [comment]
Closing this issue as #84 was merged
