### ISSUE TITLE
Supply current app id as default argument to `Authorize.opted_in`

### ISSUE THREAD

**Issue by barnjamin** [algorand-devrel/beaker#93]
https://github.com/algorand-devrel/beaker/blob/master/beaker/decorators.py#L274

**Comment by xpanvictor** [comment]
Can i use Global.current_application_id into the opted_in function

**Comment by barnjamin** [comment]
Should be able to, are you finding thats not the case?

**Comment by xpanvictor** [comment]
I meant for the issue.
